### ISSUE TITLE
Workaround for compiling against Java 8 ByteBuffer in newer Java versions

### ISSUE THREAD

**Issue by subes** [hhu-bsinfo/hadroNIO#2]
![image](https://user-images.githubusercontent.com/332937/220965370-826e99fd-2bdf-484d-af0f-dce30265aacf.png)

Call these wrapper functions (put them in some utility class) instead of calling ByteBuffer directly. That way compiling with newer Java versions is still runnable in Java 8. The trick is to bind your code to Buffer (base class of ByteBuffer), not ByteBuffer.

```
  /**
     * Workaround for java 8 compiled on java 9 or higher
     */
    public static void position(final Buffer buffer, final int position) {
        buffer.position(position);
    }

    /**
     * Workaround for java 8 compiled on java 9 or higher
     */
    public static void limit(final Buffer buffer, final int position) {
        buffer.limit(position);
    }

    /**
     * Workaround for java 8 compiled on java 9 or higher
     */
    public static void flip(final Buffer buffer) {
        buffer.flip();
    }
```

Source: https://github.com/invesdwin/invesdwin-util/blob/master/invesdwin-util-parent/invesdwin-util/src/main/java/de/invesdwin/util/streams/buffer/bytes/ByteBuffers.java

**Comment by fruhland** [comment]
Thank you for the suggestion. However, hadroNIO will soon require Java 11 and drop support for Java 8 (it already does so on the `development` branch).
Applications, that are based on Java 8, can still be accelerated using hadroNIO, they just need to be run on a Java 11 JVM.

**Comment by subes** [comment]
Ok. I noticed anyhow that I was unable to compile on Java 8 because some Gradle plugin was incompatible. We can just close this issue then.
